# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

browserify:

  # target exts to convert
  exts: [".js"]

  # use installed 'browserify'
  command: "browserify -"

  # execute `npm install` on initialize if true
  npm_install: false

  # set nvm properties if you want to use with nvm installed automatically
  nvm:

    # required modules
    modules: []

    # browserify option string
    option: ""

    # node version if you specify, or use '.nvmrc' if 'null'
    node_version: null

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Joshua Poe
email: ""
description: >- # this means to ignore newlines until "baseurl:"
  Author of "Redlining Louisville"
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "civicdata/poe-site"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-admin

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
